# Generated by Django 5.1.3 on 2024-12-10 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_doctor_is_available'),
        ('patient_app', '0007_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_names', models.CharField(max_length=100)),
                ('dosages', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('dates', models.DateField()),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='mainpage.doctor')),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='mainpage.patient')),
            ],
        ),
    ]
